name: Push
on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'prod'
      - 'uta'
      - 'qa'

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Install python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install dependencies
        run: |
          echo ${{ github.base_ref }}
          python3.9 test.py
